repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args: [--max-line-length=200,--ignore=F403,--ignore=W503]
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0  # use latest stable version
    hooks:
    -   id: commitizen
        stages: [commit-msg]
        additional_dependencies: ['markupsafe==2.0.1']
